// gallery-dl-web cookie sender — popup logic.
// Reads the user's OWN logged-in IG/FB cookies from this browser and POSTs them to the
// gallery-dl-web server (the existing PUT /api/settings/cookies endpoint). No third-party session
// is ever touched.

const $ = (id) => document.getElementById(id);

function setStatus(text, kind = "") {
  const el = $("status");
  el.textContent = text;
  el.className = kind;
}

async function getServerUrl() {
  const { serverUrl } = await chrome.storage.local.get("serverUrl");
  return (serverUrl || "").trim().replace(/\/+$/, "");
}

async function getCookies(domain) {
  // Returns all cookies for the domain (and its parent), including host-only and domain-scoped.
  return chrome.cookies.getAll({ domain });
}

function toNetscape(cookies) {
  // Build Netscape cookies.txt text: domain \t flag \t path \t secure \t expiry \t name \t value
  const lines = [
    "# Netscape HTTP Cookie File",
    "# Generated by the gallery-dl-web browser extension",
  ];
  for (const c of cookies) {
    const domain = c.domain;
    const flag = domain.startsWith(".") ? "TRUE" : "FALSE";
    const path = c.path || "/";
    const secure = c.secure ? "TRUE" : "FALSE";
    const expiry = c.expirationDate ? Math.floor(c.expirationDate) : 0;
    lines.push([domain, flag, path, secure, String(expiry), c.name, c.value].join("\t"));
  }
  return lines.join("\n");
}

async function send(payload) {
  const base = await getServerUrl();
  if (!base) {
    throw new Error("Set the gallery-dl-web server URL above first.");
  }
  const res = await fetch(`${base}/api/settings/cookies`, {
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(payload),
  });
  if (!res.ok) {
    let detail = `HTTP ${res.status}`;
    try {
      const body = await res.json();
      detail = body.detail || detail;
    } catch {
      /* keep status */
    }
    throw new Error(detail);
  }
  return res.json();
}

function renderStatus(s) {
  const parts = [];
  if (s.has_ig) parts.push("Instagram ✓");
  else parts.push("Instagram ✗");
  if (s.has_fb) parts.push("Facebook ✓");
  else parts.push("Facebook ✗");
  return parts.join("   ");
}

async function onIg() {
  setStatus("Reading Instagram cookies…");
  try {
    const cookies = await getCookies("instagram.com");
    const sid = cookies.find((c) => c.name === "sessionid");
    if (!sid) {
      throw new Error("No 'sessionid' cookie found — log into instagram.com in this browser first.");
    }
    const s = await send({ ig_sessionid: sid.value });
    setStatus("Instagram session sent.\n" + renderStatus(s), "ok");
  } catch (e) {
    setStatus(String(e.message || e), "err");
  }
}

async function onFb() {
  setStatus("Reading Facebook cookies…");
  try {
    const cookies = await getCookies("facebook.com");
    if (!cookies.length) {
      throw new Error("No Facebook cookies found — log into facebook.com in this browser first.");
    }
    const text = toNetscape(cookies);
    const s = await send({ fb_cookies_text: text });
    setStatus("Facebook cookies sent.\n" + renderStatus(s), "ok");
  } catch (e) {
    setStatus(String(e.message || e), "err");
  }
}

async function onCheck() {
  setStatus("Checking…");
  try {
    const base = await getServerUrl();
    if (!base) throw new Error("Set the gallery-dl-web server URL above first.");
    const res = await fetch(`${base}/api/settings`);
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    const s = await res.json();
    setStatus("Server status:\n" + renderStatus(s), "ok");
  } catch (e) {
    setStatus(String(e.message || e), "err");
  }
}

async function onClear() {
  setStatus("Clearing…");
  try {
    const s = await send({ ig_sessionid: "", fb_cookies_text: "" });
    setStatus("Cleared both.\n" + renderStatus(s), "ok");
  } catch (e) {
    setStatus(String(e.message || e), "err");
  }
}

async function init() {
  const { serverUrl } = await chrome.storage.local.get("serverUrl");
  $("server").value = serverUrl || "";
  $("server").addEventListener("change", async (e) => {
    await chrome.storage.local.set({ serverUrl: e.target.value.trim() });
    setStatus("Server URL saved.", "ok");
  });
  $("ig").addEventListener("click", onIg);
  $("fb").addEventListener("click", onFb);
  $("check").addEventListener("click", onCheck);
  $("clear").addEventListener("click", onClear);
}

init();
